export const ADD_BEVERAGE = 'ADD_BEVERAGE';
export const INCREMENT_BEVERAGE = 'INCREMENT_BEVERAGE';
export const REDUCE_BEVERAGE = 'REDUCE_BEVERAGE';
export const REMOVE_BEVERAGE = 'REMOVE_BEVERAGE';
export const REMOVE_ALL_BEVERAGES = 'REMOVE_ALL_BEVERAGES';
export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';

export const SET_MEETING_ROOM = 'SET_MEETING_ROOM';